language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

sudo: required

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install zookeeper zookeeperd -y
  - sudo pip install cocaine cocaine-tools
  - docker pull noxiouz/cocaine
  - docker run -d --net=host noxiouz/cocaine && docker ps

install:
  - "pip install tox tox-travis python-coveralls"

script: tox

notifications:
  slack: cocaine:qDewv6ZVDt0TciQeNdE47GqG

branches:
  only:
    - master
    - v0.11
    - v0.12

after_success: coveralls
